#!/bin/sh
modprobe zram
ram=$(cat /proc/meminfo | awk '/MemTotal/{ print $2 }')

echo -n lzo-rle > /sys/block/zram0/comp_algorithm
echo -n $((ram * 2 / 4))K > /sys/block/zram0/disksize
mkswap /dev/zram0
swapon /dev/zram0
exec permafrost
